services:
  - type: web
    name: zenith-crm-backend
    env: python
    region: oregon
    plan: starter
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: gunicorn zenith_crm.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /api/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: zenith_crm.settings
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: USE_SQLITE
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
        value: zenith-crm-backend.onrender.com

  - type: web
    name: zenith-crm-frontend
    env: static
    region: oregon
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
        value: https://zenith-crm-backend.onrender.com/api

databases:
  - name: zenith-crm-db
    databaseName: zenith_crm
    user: zenith_user
    plan: starter
    region: oregon
